# Generated by Django 3.2.25 on 2024-04-29 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='usersubscription',
            options={'verbose_name': 'Subscribed User', 'verbose_name_plural': 'Subscribed Users'},
        ),
        migrations.AddField(
            model_name='usersubscription',
            name='subscription_name',
            field=models.CharField(default='testing', max_length=40),
            preserve_default=False,
        ),
    ]
