# Generated by Django 3.2.25 on 2024-04-29 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0002_auto_20240429_1634'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscription',
            name='promotional_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
    ]
