# Generated by Django 3.2.25 on 2024-05-10 20:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0003_alter_subscription_promotional_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='Playlist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('friendly_name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('number', models.IntegerField()),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to='')),
                ('img_url', models.URLField(blank=True, max_length=1024, null=True)),
                ('text', models.TextField(blank=True, null=True)),
                ('video_url', models.URLField(blank=True, max_length=1024, null=True)),
                ('playlist', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='lessons.playlist')),
            ],
        ),
    ]
