# Generated by Django 3.2.25 on 2024-05-13 17:03

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0005_auto_20240513_1628'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscription',
            name='image',
            field=cloudinary.models.CloudinaryField(blank=True, default='placeholder', max_length=255, null=True, verbose_name='image'),
        ),
    ]
