# Generated by Django 3.2.25 on 2024-05-13 21:03

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0006_alter_subscription_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscription',
            name='image',
            field=cloudinary.models.CloudinaryField(blank=True, default=None, max_length=255, null=True, verbose_name='image'),
        ),
    ]
